var redis = require('../system/core/redisFactory');
redis.set('rhcs:celestia_thing:0', '{"parent": "celone", "description": "Кабинет", "type": "do", "pin": 22, "value": 0}');
redis.set('rhcs:celestia_thing:1', '{"parent": "celone", "description": "Чайник", "type": "do", "pin": 23, "value": 0}');
redis.set('rhcs:celestia_thing:2', '{"parent": "celone", "description": "Большая аудитория", "type": "do", "pin": 24, "value": 0}');
redis.set('rhcs:celestia_thing:3', '{"parent": "celone", "description": "Склад", "type": "do", "pin": 25, "value": 0}');
redis.set('rhcs:celestia_thing:4', '{"parent": "celone", "description": "Подсветка #1", "type": "ao", "pin": 13, "value": 0}');
redis.set('rhcs:celestia_thing:5', '{"parent": "celone", "description": "Подсветка #2", "type": "ao", "pin": 3, "value": 0}');
redis.set('rhcs:celestia_thing:6', '{"parent": "celone", "description": "Robot One", "type": "xbs_robot", "rID": "00A1" }');
redis.set('rhcs:celestia_thing:8', '{"parent": "celone", "description": "Robot Two", "type": "xbs_robot", "rID": "00A2 }');
redis.set('rhcs:celestia_thing:9', '{"parent": "celone", "description": "HVAC", "type": "r433_irsend_hvac", "rID": "005A }');
redis.set('rhcs:celestia_thing:10', '{"parent": "celone", "description": "Розетка", "type": "do", "pin": 27, "value": 0}');